version: "3"

# More info at https://github.com/pi-hole/docker-pi-hole/ and https://docs.pi-hole.net/
services:
  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "67:67/udp"
      - "547:547/tcp"
      - "547:547/udp"
      - "4711:4711/tcp"
      - "4711:4711/udp"
      - "80:80/tcp"
      - "443:443/tcp"
    environment:
      TZ: 'America/Tijuana'
      WEBPASSWORD: 'admin@123'
      IPv6: 'true'
      PIHOLE_DNS_: '10.0.0.2#5053;1.1.1.1'
    volumes:
      - '.:/app'
      - './etc-pihole/:/etc/pihole/'
      - './etc-dnsmasq.d/:/etc/dnsmasq.d/'
    restart: unless-stopped
