version: "3"

# More info at https://github.com/pi-hole/docker-pi-hole/ and https://docs.pi-hole.net/
services:
  pihole:
    image: pihole/pihole:2022.09.4
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "67:67/udp"
      - "547:547/tcp"
      - "547:547/udp"
      - "4711:4711/tcp"
      - "4711:4711/udp"
      - "80:80/tcp"
      - "443:443/tcp"
      - "22"
    environment:
      TZ: "America/Tijuana"
      IPv6: "true"
      PIHOLE_DNS_: "10.0.0.2#5053;1.1.1.1"
      ServerIP: ${ServerIPv4}
      ServerIPv6: ${ServerIPv6}
    volumes:
      - "./scripts:/scripts"
      - "./url-lists:/url-lists"
      - "./etc-pihole/:/etc/pihole/"
      - "./etc-dnsmasq.d/:/etc/dnsmasq.d/"
      - "./resolv.conf:/etc/resolv.conf:ro"
    restart: unless-stopped
